spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8088/realms/ecommerce-realm/protocol/openid-connect/certs"